# Generated by Django 5.0.6 on 2024-06-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_favorites_options_alter_games_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('step', models.IntegerField(verbose_name='Шаг')),
                ('image', models.ImageField(null=True, upload_to='images', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='images', verbose_name='Фото')),
                ('description', models.CharField(max_length=4096, verbose_name='Описание')),
                ('cookingFullTime', models.DateTimeField()),
                ('cookingTime', models.DateTimeField()),
                ('portions', models.IntegerField()),
                ('lvlComplexity', models.IntegerField()),
                ('idGame', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='favorites',
            name='idRecipe',
            field=models.IntegerField(verbose_name='ИД Рецепта'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='idUser',
            field=models.IntegerField(verbose_name='ИД Пользователя'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
