# Generated by Django 5.0.6 on 2024-06-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_instructions_recipes_alter_favorites_idrecipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField()),
                ('idRecipe', models.IntegerField()),
                ('lvl', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='recipes',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
