# Generated by Django 5.0.6 on 2024-06-05 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_recipes_idgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='idGenre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genres'),
        ),
    ]
