# Generated by Django 5.0.6 on 2024-06-05 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_games_idgenre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField()),
                ('idRecipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipes')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.AlterModelOptions(
            name='instructions',
            options={'verbose_name': 'Игридиент для рецепта', 'verbose_name_plural': 'Игридиенты для рецептов'},
        ),
        migrations.AddField(
            model_name='instructions',
            name='idRecipe',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='main.recipes'),
        ),
        migrations.AddField(
            model_name='nutritionals',
            name='idRecipe',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='main.recipes'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='description',
            field=models.CharField(max_length=2056, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='idIngredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredients'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='idRecipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipes'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='idUnit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.units'),
        ),
    ]
