# Generated by Django 5.0.6 on 2024-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_grades_delete_grade_alter_instructions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipes',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipes',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipes',
            name='squirrels',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Nutritionals',
        ),
    ]
