# Generated by Django 5.0.6 on 2024-06-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_recipes_calories_recipes_carbohydrates_recipes_fats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructions',
            options={'verbose_name': 'Инструкция для рецепта', 'verbose_name_plural': 'Инструкции для рецепта'},
        ),
        migrations.AddField(
            model_name='recipes',
            name='nameInGame',
            field=models.CharField(default='Неизвестно', max_length=256, verbose_name='Как называется в игре'),
        ),
    ]
