# Generated by Django 5.0.6 on 2024-06-05 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_instructions_options_recipes_nameingame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='idRecipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipes'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
